# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a544f3d8f2c86ccb743d2efcf71770299a3a89530d32803123e440172209454517da011240031d1aa09a4fcefeed73252bbad96d9d658009de9c75e67756cabf

test:
  secret_key_base: 7862b35c4ac54ca11e67c134aa34170657fea940e8bfd59c70fce6b2355f9aa3cf34e84c59093a887cda90bfbf6e55d3a5013fab71ab7380209d0a6da5d3978e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
